services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sam-express-typescript
    ports:
      - 8080:8080
    volumes:
      - ./app:/app
      - node-modules:/app/node_modules
    depends_on:
      - dynamodb-local
    environment:
      ENV: "docker"
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
volumes:
  node-modules:
